export enum ValidModules {
  super = 'super',

  bateria = 'bateria',
  bateriaCreate = 'bateria-create',
  bateriaAll = 'bateria-all',
  bateriaOne = 'bateria-one',
  bateriaUpdate = 'bateria-update',
  bateriaRemove = 'bateria-remove',

  bloque = 'bloque',
  bloqueCreate = 'bloque-create',
  bloqueAll = 'bloque-all',
  bloqueOne = 'bloque-one',
  bloqueUpdate = 'bloque-update',
  bloqueRemove = 'bloque-remove',

  capa = 'capa',
  capaCreate = 'capa-create',
  capaAll = 'capa-all',
  capaOne = 'capa-one',
  capaUpdate = 'capa-update',
  capaRemove = 'capa-remove',

  cliente = 'cliente',
  clienteCreate = 'cliente-create',
  clienteAll = 'cliente-all',
  clienteOne = 'cliente-one',
  clienteUpdate = 'cliente-update',
  clienteRemove = 'cliente-remove',

  control = 'control',
  controlCreate = 'control-create',
  controlAll = 'control-all',
  controlOne = 'control-one',
  controlUpdate = 'control-update',
  controlRemove = 'control-remove',

  downtime = 'downtime',
  downtimeCreate = 'downtime-create',
  downtimeAll = 'downtime-all',
  downtimeOne = 'downtime-one',
  downtimeUpdate = 'downtime-update',
  downtimeRemove = 'downtime-remove',

  distribucionPorCapas = 'distribucion-por-capas',
  distribucionPorCapasCreate = 'distribucion-por-capas-create',
  distribucionPorCapasAll = 'distribucion-por-capas-all',
  distribucionPorCapasOne = 'distribucion-por-capas-one',
  distribucionPorCapasUpdate = 'distribucion-por-capas-update',
  distribucionPorCapasRemove = 'distribucion-por-capas-remove',

  compresor = 'compresor',
  compresorCreate = 'compresor-create',
  compresorAll = 'compresor-all',
  compresorOne = 'compresor-one',
  compresorUpdate = 'compresor-update',
  compresorRemove = 'compresor-remove',

  derivadoRecibido = 'derivado-recibido',
  derivadoRecibidoCreate = 'derivado-recibido-create',
  derivadoRecibidoAll = 'derivado-recibido-all',
  derivadoRecibidoOne = 'derivado-recibido-one',
  derivadoRecibidoUpdate = 'derivado-recibido-update',
  derivadoRecibidoRemove = 'derivado-recibido-remove',

  clienteDerivadoRecibido = 'cliente-derivado-recibido',
  clienteDerivadoRecibidoCreate = 'cliente-derivado-recibido-create',
  clienteDerivadoRecibidoAll = 'cliente-derivado-recibido-all',
  clienteDerivadoRecibidoOne = 'cliente-derivado-recibido-one',
  clienteDerivadoRecibidoUpdate = 'cliente-derivado-recibido-update',
  clienteDerivadoRecibidoRemove = 'cliente-derivado-recibido-remove',

  causaDowntimeNivel1 = 'causa-downtime-nivel-1',
  causaDowntimeNivel1Create = 'causa-downtime-nivel-1-create',
  causaDowntimeNivel1All = 'causa-downtime-nivel-1-all',
  causaDowntimeNivel1One = 'causa-downtime-nivel-1-one',
  causaDowntimeNivel1Update = 'causa-downtime-nivel-1-update',
  causaDowntimeNivel1Remove = 'causa-downtime-nivel-1-remove',

  causaDowntimeNivel2 = 'causa-downtime-nivel-2',
  causaDowntimeNivel2Create = 'causa-downtime-nivel-2-create',
  causaDowntimeNivel2All = 'causa-downtime-nivel-2-all',
  causaDowntimeNivel2One = 'causa-downtime-nivel-2-one',
  causaDowntimeNivel2Update = 'causa-downtime-nivel-2-update',
  causaDowntimeNivel2Remove = 'causa-downtime-nivel-2-remove',

  causaDowntimeNivel3 = 'causa-downtime-nivel-3',
  causaDowntimeNivel3Create = 'causa-downtime-nivel-3-create',
  causaDowntimeNivel3All = 'causa-downtime-nivel-3-all',
  causaDowntimeNivel3One = 'causa-downtime-nivel-3-one',
  causaDowntimeNivel3Update = 'causa-downtime-nivel-3-update',
  causaDowntimeNivel3Remove = 'causa-downtime-nivel-3-remove',

  causaDowntimeNivel4 = 'causa-downtime-nivel-4',
  causaDowntimeNivel4Create = 'causa-downtime-nivel-4-create',
  causaDowntimeNivel4All = 'causa-downtime-nivel-4-all',
  causaDowntimeNivel4One = 'causa-downtime-nivel-4-one',
  causaDowntimeNivel4Update = 'causa-downtime-nivel-4-update',
  causaDowntimeNivel4Remove = 'causa-downtime-nivel-4-remove',

  causaDowntimeNivel5 = 'causa-downtime-nivel-5',
  causaDowntimeNivel5Create = 'causa-downtime-nivel-5-create',
  causaDowntimeNivel5All = 'causa-downtime-nivel-5-all',
  causaDowntimeNivel5One = 'causa-downtime-nivel-5-one',
  causaDowntimeNivel5Update = 'causa-downtime-nivel-5-update',
  causaDowntimeNivel5Remove = 'causa-downtime-nivel-5-remove',

  causaDowntimeNivel6 = 'causa-downtime-nivel-6',
  causaDowntimeNivel6Create = 'causa-downtime-nivel-6-create',
  causaDowntimeNivel6All = 'causa-downtime-nivel-6-all',
  causaDowntimeNivel6One = 'causa-downtime-nivel-6-one',
  causaDowntimeNivel6Update = 'causa-downtime-nivel-6-update',
  causaDowntimeNivel6Remove = 'causa-downtime-nivel-6-remove',

  entidadRelacion = 'entidad-relacion',
  entidadRelacionCreate = 'entidad-relacion-create',
  entidadRelacionAll = 'entidad-relacion-all',
  entidadRelacionOne = 'entidad-relacion-one',
  entidadRelacionUpdate = 'entidad-relacion-update',
  entidadRelacionRemove = 'entidad-relacion-remove',

  entidadmodelo = 'entidadmodelo',
  entidadmodeloCreate = 'entidadmodelo-create',
  entidadmodeloAll = 'entidadmodelo-all',
  entidadmodeloOne = 'entidadmodelo-one',
  entidadmodeloUpdate = 'entidadmodelo-update',
  entidadmodeloRemove = 'entidadmodelo-remove',

  entrega = 'entrega',
  entregaCreate = 'entrega-create',
  entregaAll = 'entrega-all',
  entregaOne = 'entrega-one',
  entregaUpdate = 'entrega-update',

  estadoPozo = 'estado-pozo',
  estadoPozoCreate = 'estado-pozo-create',
  estadoPozoAll = 'estado-pozo-all',
  estadoPozoOne = 'estado-pozo-one',
  estadoPozoUpdate = 'estado-pozo-update',
  estadoPozoRemove = 'estado-pozo-remove',

  inyeccionProducto = 'inyeccion-producto',
  inyeccionProductoCreate = 'inyeccion-producto-create',
  inyeccionProductoAll = 'inyeccion-producto-all',
  inyeccionProductoOne = 'inyeccion-producto-one',
  inyeccionProductoUpdate = 'inyeccion-producto-update',
  inyeccionProductoRemove = 'inyeccion-producto-remove',

  inyeccionPurga = 'inyeccion-purga',
  inyeccionPurgaCreate = 'inyeccion-purga-create',
  inyeccionPurgaAll = 'inyeccion-purga-all',
  inyeccionPurgaOne = 'inyeccion-purga-one',
  inyeccionPurgaUpdate = 'inyeccion-purga-update',
  inyeccionPurgaRemove = 'inyeccion-purga-remove',

  plantaGas = 'planta-gas',
  plantaGasCreate = 'planta-gas-create',
  plantaGasAll = 'planta-gas-all',
  plantaGasOne = 'planta-gas-one',
  plantaGasUpdate = 'planta-gas-update',
  plantaGasRemove = 'planta-gas-remove',

  potencialInyeccion = 'potencial-inyeccion',
  potencialInyeccionCreate = 'potencial-inyeccion-create',
  potencialInyeccionAll = 'potencial-inyeccion-all',
  potencialInyeccionOne = 'potencial-inyeccion-one',
  potencialInyeccionUpdate = 'potencial-inyeccion-update',
  potencialInyeccionRemove = 'potencial-inyeccion-remove',

  potencial = 'potencial',
  potencialCreate = 'potencial-create',
  potencialAll = 'potencial-all',
  potencialOne = 'potencial-one',
  potencialUpdate = 'potencial-update',
  potencialRemove = 'potencial-remove',

  pozo = 'pozo',
  pozoCreate = 'pozo-create',
  pozoAll = 'pozo-all',
  pozoOne = 'pozo-one',
  pozoUpdate = 'pozo-update',
  pozoRemove = 'pozo-remove',

  pozoEstadoActual = 'pozo-estado-actual',
  pozoEstadoActualCreate = 'pozo-estado-actual-create',
  pozoEstadoActualAll = 'pozo-estado-actual-all',
  pozoEstadoActualOne = 'pozo-estado-actual-one',
  pozoEstadoActualUpdate = 'pozo-estado-actual-update',
  pozoEstadoActualRemove = 'pozo-estado-actual-remove',

  presionesDePozo = 'presiones-de-pozo',
  presionesDePozoCreate = 'presiones-de-pozo-create',
  presionesDePozoAll = 'presiones-de-pozo-all',
  presionesDePozoOne = 'presiones-de-pozo-one',
  presionesDePozoUpdate = 'presiones-de-pozo-update',
  presionesDePozoRemove = 'presiones-de-pozo-remove',

  productoInyeccion = 'producto-inyeccion',
  productoInyeccionCreate = 'producto-inyeccion-create',
  productoInyeccionAll = 'producto-inyeccion-all',
  productoInyeccionOne = 'producto-inyeccion-one',
  productoInyeccionUpdate = 'producto-inyeccion-update',
  productoInyeccionRemove = 'producto-inyeccion-remove',

  producto = 'producto',
  productoCreate = 'producto-create',
  productoAll = 'producto-all',
  productoOne = 'producto-one',
  productoUpdate = 'producto-update',
  productoRemove = 'producto-remove',

  puntoMuestreo = 'punto-muestreo',
  puntoMuestreoCreate = 'punto-muestreo-create',
  puntoMuestreoAll = 'punto-muestreo-all',
  puntoMuestreoOne = 'punto-muestreo-one',
  puntoMuestreoUpdate = 'punto-muestreo-update',
  puntoMuestreoRemove = 'punto-muestreo-remove',

  satelite = 'satelite',
  sateliteCreate = 'satelite-create',
  sateliteAll = 'satelite-all',
  sateliteOne = 'satelite-one',
  sateliteUpdate = 'satelite-update',
  sateliteRemove = 'satelite-remove',

  separadorDiario = 'separador-diario',
  separadorDiarioCreate = 'separador-diario-create',
  separadorDiarioAll = 'separador-diario-all',
  separadorDiarioOne = 'separador-diario-one',
  separadorDiarioUpdate = 'separador-diario-update',
  separadorDiarioRemove = 'separador-diario-remove',

  separador = 'separador',
  separadorCreate = 'separador-create',
  separadorAll = 'separador-all',
  separadorOne = 'separador-one',
  separadorUpdate = 'separador-update',
  separadorRemove = 'separador-remove',

  sistemaExtraccion = 'sistema-extraccion',
  sistemaExtraccionCreate = 'sistema-extraccion-create',
  sistemaExtraccionAll = 'sistema-extraccion-all',
  sistemaExtraccionOne = 'sistema-extraccion-one',
  sistemaExtraccionUpdate = 'sistema-extraccion-update',
  sistemaExtraccionRemove = 'sistema-extraccion-remove',

  stockBateriaDiario = 'stock-bateria-diario',
  stockBateriaDiarioCreate = 'stock-bateria-diario-create',
  stockBateriaDiarioAll = 'stock-bateria-diario-all',
  stockBateriaDiarioOne = 'stock-bateria-diario-one',
  stockBateriaDiarioUpdate = 'stock-bateria-diario-update',
  stockBateriaDiarioRemove = 'stock-bateria-diario-remove',

  stockReguladoDiario = 'stock-regulado-diario',
  stockReguladoDiarioCreate = 'stock-regulado-diario-create',
  stockReguladoDiarioAll = 'stock-regulado-diario-all',
  stockReguladoDiarioOne = 'stock-regulado-diario-one',
  stockReguladoDiarioUpdate = 'stock-regulado-diario-update',
  stockReguladoDiarioRemove = 'stock-regulado-diario-remove',

  stockRegulado = 'stock-regulado',
  stockReguladoCreate = 'stock-regulado-create',
  stockReguladoAll = 'stock-regulado-all',
  stockReguladoOne = 'stock-regulado-one',
  stockReguladoUpdate = 'stock-regulado-update',
  stockReguladoRemove = 'stock-regulado-remove',

  tanqueDiario = 'tanque-diario',
  tanqueDiarioCreate = 'tanque-diario-create',
  tanqueDiarioAll = 'tanque-diario-all',
  tanqueDiarioOne = 'tanque-diario-one',
  tanqueDiarioUpdate = 'tanque-diario-update',
  tanqueDiarioRemove = 'tanque-diario-remove',

  tanque = 'tanque',
  tanqueCreate = 'tanque-create',
  tanqueAll = 'tanque-all',
  tanqueOne = 'tanque-one',
  tanqueUpdate = 'tanque-update',
  tanqueRemove = 'tanque-remove',

  tipoEntrega = 'tipo-entrega',
  tipoEntregaCreate = 'tipo-entrega-create',
  tipoEntregaAll = 'tipo-entrega-all',
  tipoEntregaOne = 'tipo-entrega-one',
  tipoEntregaUpdate = 'tipo-entrega-update',
  tipoEntregaRemove = 'tipo-entrega-remove',

  tipoPozo = 'tipo-pozo',
  tipoPozoCreate = 'tipo-pozo-create',
  tipoPozoAll = 'tipo-pozo-all',
  tipoPozoOne = 'tipo-pozo-one',
  tipoPozoUpdate = 'tipo-pozo-update',
  tipoPozoRemove = 'tipo-pozo-remove',

  tipoProducto = 'tipo-producto',
  tipoProductoCreate = 'tipo-producto-create',
  tipoProductoAll = 'tipo-producto-all',
  tipoProductoOne = 'tipo-producto-one',
  tipoProductoUpdate = 'tipo-producto-update',
  tipoProductoRemove = 'tipo-producto-remove',

  yacimiento = 'yacimiento',
  yacimientoCreate = 'yacimiento-create',
  yacimientoAll = 'yacimiento-all',
  yacimientoOne = 'yacimiento-one',
  yacimientoUpdate = 'yacimiento-update',
  yacimientoRemove = 'yacimiento-remove',

  produccionLiquidos = 'produccion-liquidos',
  produccionLiquidosCreate = 'produccion-liquidos-create',
  produccionLiquidosAll = 'produccion-liquidos-all',
  produccionLiquidosOne = 'produccion-liquidos-one',
  produccionLiquidosUpdate = 'produccion-liquidos-update',
  produccionLiquidosRemove = 'produccion-liquidos-remove',

  produccionOil = 'produccion-oil',
  produccionOilCreate = 'produccion-oil-create',
  produccionOilAll = 'produccion-oil-all',
  produccionOilOne = 'produccion-oil-one',
  produccionOilUpdate = 'produccion-oil-update',
  produccionOilRemove = 'produccion-oil-delete',

  produccionDiaria = 'produccion-diaria',
  produccionDiariaCreate = 'produccion-diaria-create',
  produccionDiariaGetAll = 'produccion-diaria-all',
  produccionDiariaGetOne = 'produccion-diaria-one',
  produccionDiariaUpdate = 'produccion-diaria-update',
  produccionDiariaRemove = 'produccion-diaria-delete',

  produccionOilObservaciones = 'produccion-oil-observaciones',
  produccionOilObservacionesCreate = 'produccion-oil-observaciones-create',
  produccionOilObservacionesGetAll = 'produccion-oil-observaciones-all',
  produccionOilObservacionesGetOne = 'produccion-oil-observaciones-one',
  produccionOilObservacionesUpdate = 'produccion-oil-observaciones-update',
  produccionOilObservacionesRemove = 'produccion-oil-observaciones-delete',

  produccionPozosDiaria = 'produccion-pozos-diaria',
  produccionPozosDiariaCreate = 'produccion-pozos-diaria-create',
  produccionPozosDiariaGetAll = 'produccion-pozos-diaria-all',
  produccionPozosDiariaGetOne = 'produccion-pozos-diaria-one',
  produccionPozosDiariaUpdate = 'produccion-pozos-diaria-update',
  produccionPozosDiariaRemove = 'produccion-pozos-diaria-delete',

  factorAjusteSigma = 'factor-ajuste-sigma',
  factorAjusteSigmaCreate = 'factor-ajuste-sigma-create',
  factorAjusteSigmaGetAll = 'factor-ajuste-sigma-all',
  factorAjusteSigmaGetOne = 'factor-ajuste-sigma-one',
  factorAjusteSigmaUpdate = 'factor-ajuste-sigma-update',
  factorAjusteSigmaRemove = 'factor-ajuste-sigma-delete',

  historiaProduccionCia = 'historia-produccion-cia',
  historiaProduccionCiaCreate = 'historia-produccion-cia-create',
  historiaProduccionCiaGetAll = 'historia-produccion-cia-all',
  historiaProduccionCiaGetOne = 'historia-produccion-cia-one',
  historiaProduccionCiaUpdate = 'historia-produccion-cia-update',
  historiaProduccionCiaRemove = 'historia-produccion-cia-delete',

  historiaProduccionPozos = 'historia-produccion-pozos',
  historiaProduccionPozosCreate = 'historia-produccion-pozos-create',
  historiaProduccionPozosGetAll = 'historia-produccion-pozos-all',
  historiaProduccionPozosGetOne = 'historia-produccion-pozos-one',
  historiaProduccionPozosUpdate = 'historia-produccion-pozos-update',
  historiaProduccionPozosRemove = 'historia-produccion-pozos-delete',

  cierrePozoMensual = 'cierre-pozo-mensual',
  cierrePozoMensualCreate = 'cierre-pozo-mensual-create',
  cierrePozoMensualGetAll = 'cierre-pozo-mensual-all',
  cierrePozoMensualGetOne = 'cierre-pozo-mensual-one',
  cierrePozoMensualUpdate = 'cierre-pozo-mensual-update',
  cierrePozoMensualRemove = 'cierre-pozo-mensual-delete',

  historiaProduccionPozosGas = 'historia-produccion-pozos-gas',
  historiaProduccionPozosGasCreate = 'historia-produccion-pozos-gas-create',
  historiaProduccionPozosGasGetAll = 'historia-produccion-pozos-gas-all',
  historiaProduccionPozosGasGetOne = 'historia-produccion-pozos-gas-one',
  historiaProduccionPozosGasUpdate = 'historia-produccion-pozos-gas-update',
  historiaProduccionPozosGasRemove = 'historia-produccion-pozos-gas-delete',

  logPartes = 'log-partes',
  logPartesCreate = 'log-partes-create',
  logPartesGetAll = 'log-partes-all',
  logPartesGetOne = 'log-partes-one',
  logPartesUpdate = 'log-partes-update',
  logPartesRemove = 'log-partes-delete',

  produccionLiquidosGas = 'produccion-liquidos-gas',
  produccionLiquidosGasCreate = 'produccion-liquidos-gas-create',
  produccionLiquidosGasGetAll = 'produccion-liquidos-gas-all',
  produccionLiquidosGasGetOne = 'produccion-liquidos-gas-one',
  produccionLiquidosGasUpdate = 'produccion-liquidos-gas-update',
  produccionLiquidosGasRemove = 'produccion-liquidos-gas-delete',

  parteDiario = 'parte-diario',
  parteDiarioCreate = 'parte-diario-create',
  parteDiarioAll = 'parte-diario-all',
  parteDiarioGetOne = 'parte-diario-one',
  parteDiarioUpdate = 'parte-diario-update',
  parteDiarioRemove = 'parte-diario-delete',

  //TemplateValidModules
  template = 'template',
  templateAll = 'templateGetAll',
  templateOne = 'templateGetOne',
  templateCreate = 'templateCreate',
  templateRemove = 'templateDelete',
  templateUpdate = 'templateUpdate',
  //NO BORRAR LA LINEA DE ARRIBA
}
