version: '3.8'
services:
  dbpg:
    image: postgres:15.4
    restart: always
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: ${PG_DB_USERNAME}
      POSTGRES_PASSWORD: ${PG_DB_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    container_name: boiler-00
    volumes:
      - ./postgres:/var/lib/posgresql/data

volumes:
  todo_db: {}
